USE DEVDBNEW
GO

--truncate table invproductmaster

INSERT INTO [dbo].[InvProductMaster]
           ([ProductCode]
           ,[BarCode]
           ,[BarCode2]
           ,[ReferenceCode1]
           ,[ReferenceCode2]
           ,[ReferenceCode3]
           ,[ProductName]
           ,[NameOnInvoice]
           ,[DepartmentID]
           ,[CategoryID]
           ,[SubCategoryID]
           ,[SubCategory2ID]
           ,[SubCategory3ID]
           ,[ColorID]
           ,[SizeID]
           ,[WarrantyID]
           ,[BrandID]
           ,[ModelID]
           ,[PatternID]
           ,[InvProductTypeID]
           ,[InvKitchenBarID]
           ,[SupplierID]
           ,[UnitOfMeasureID]
           ,[PackSize]
           ,[ProductImage]
           ,[CostingMethod]
           ,[CostPrice]
           ,[OrderPrice]
           ,[AverageCost]
           ,[SellingPrice]
           ,[WholesalePrice]
           ,[MinimumPrice]
           ,[FixedDiscount]
           ,[MaximumDiscount]
           ,[MaximumPrice]
           ,[FixedDiscountPercentage]
           ,[MaximumDiscountPercentage]
           ,[ReOrderLevel]
           ,[ReOrderQty]
           ,[TotalStockQty]
           ,[ReOrderPeriod]
           ,[IsActive]
           ,[IsBatch]
           ,[IsPromotion]
           ,[IsBundle]
           ,[IsFreeIssue]
           ,[IsDrayage]
           ,[IsWarranty]
           ,[IsPriceLink]
           ,[IsReplenished]
           ,[DrayagePercentage]
           ,[IsExpiry]
           ,[IsConsignment]
           ,[IsCountable]
           ,[IsDCS]
           ,[DcsID]
           ,[ConsignmentDateOfComplete]
           ,[IsTax]
           ,[IsSerial]
           ,[IsNonExchangeable]
           ,[IsNonDiscount]
           ,[IsColorSize]
           ,[IsECommerce]
           ,[IsBulkQty]
           ,[IsDelete]
           ,[PackSizeUnitOfMeasureID]
           ,[Margin]
           ,[WholesaleMargin]
           ,[FixedGP]
           ,[QCTime]
           ,[PurchaseLedgerID]
           ,[SalesLedgerID]
           ,[OtherPurchaseLedgerID]
           ,[OtherSalesLedgerID]
           ,[IsNoneExchangeable]
           ,[Remark]
           ,[LaunchDate]
           ,[OnlineName]
           ,[ECommerceDescription]
           ,[ECommerceSortOrder]
           ,[ECommerceMetaTitle]
           ,[ECommerceMetaKeyword]
           ,[ECommerceMetaDescription]
           ,[GroupOfCompanyID]
           ,[CreatedUser]
           ,[CreatedDate]
           ,[ModifiedUser]
           ,[ModifiedDate]
           ,[DataTransfer]
           ,[Department]
           ,[Category]
           ,[SubCategory]
           ,[SubCategory2]
           ,[Supplier]
           ,[SubCategory3]
           ,[IsMultiplePrice]
           ,[IsReOrder]
           ,[StyleNo]
           ,[IsNonTrading])
   --select * from TFSMIG.dbo.Products 
	select 
	 ''[ProductCode]
           ,isnull(NEWBARCODE,'')
           ,'' [BarCode2]
           ,ISNULL(NEWITEMCODE,'')[ReferenceCode1]
           ,isnull([STYLE NUMBER],'')  [ReferenceCode2]
           ,''[ReferenceCode3]
           ,  isnull([NEW DESCRIPITION],'')
           ,isnull([NEW DESCRIPITION],'') [NameOnInvoice]
           ,1 [DepartmentID]
           ,1[CategoryID]
           ,1[SubCategoryID]
           ,1 [SubCategory2ID]
           ,1 [SubCategory3ID]
           ,1 [ColorID]
           ,1 [SizeID]
           ,1 [WarrantyID]
           ,1 [BrandID]
           ,1 [ModelID]
           ,1 [PatternID]
           ,1 [InvProductTypeID]
           ,0 [InvKitchenBarID]
           ,1 [SupplierID]
           ,1 [UnitOfMeasureID]
           ,1 [PackSize]
           ,null [ProductImage]
           ,1 [CostingMethod]
           ,isnull([Cost Price],0)
           ,0 [OrderPrice]
           ,0 [AverageCost]
           ,isnull([Selling Price],0)
           ,isnull([Selling Price],0) [WholesalePrice]
           ,isnull([Cost Price],0) [MinimumPrice]
           ,0 [FixedDiscount]
           ,0 [MaximumDiscount]
           ,isnull([Selling Price],0) [MaximumPrice]
           ,0 [FixedDiscountPercentage]
           ,0 [MaximumDiscountPercentage]
           ,0 [ReOrderLevel]
           ,0 [ReOrderQty]
           ,0 [TotalStockQty]
           ,0 [ReOrderPeriod]
           ,1 [IsActive]
           ,0 [IsBatch]
           ,0 [IsPromotion]
           ,0 [IsBundle]
           ,0 [IsFreeIssue]
           ,0 [IsDrayage]
           ,0 [IsWarranty]
           ,0 [IsPriceLink]
           ,0 [IsReplenished]
           ,0 [DrayagePercentage]
           ,0 [IsExpiry]
           ,0 [IsConsignment]
           ,1 [IsCountable]
           ,0 [IsDCS]
           ,0 [DcsID]
           ,0 [ConsignmentDateOfComplete]
           ,0 [IsTax]
           ,0 [IsSerial]
           ,0 [IsNonExchangeable]
           ,0 [IsNonDiscount]
           ,0 [IsColorSize]
           ,0 [IsECommerce]
           ,0 [IsBulkQty]
           ,0 [IsDelete]
           ,1 [PackSizeUnitOfMeasureID]
           ,0 [Margin]
           ,0 [WholesaleMargin]
           ,0 [FixedGP]
           ,0 [QCTime]
           ,0 [PurchaseLedgerID]
           ,0 [SalesLedgerID]
           ,0 [OtherPurchaseLedgerID]
           ,0 [OtherSalesLedgerID]
           ,0 [IsNoneExchangeable]
           ,'' [Remark]
           ,getdate() [LaunchDate]
           ,'' [OnlineName]
           ,''[ECommerceDescription]
           ,''[ECommerceSortOrder]
           ,''[ECommerceMetaTitle]
           ,''[ECommerceMetaKeyword]
           ,''[ECommerceMetaDescription]
           ,103 [GroupOfCompanyID]
           ,'SARASA' [CreatedUser]
           ,Getdate() [CreatedDate]
           ,'SARASA'[ModifiedUser]
           ,Getdate() [ModifiedDate]
           ,0[DataTransfer]
           ,DEPARTMENT[Department]
           ,[SUB DEPARTMENT][Category]
           ,category[SubCategory]
           ,SUBcategory[SubCategory2]
           ,supplier[Supplier]
           ,''[SubCategory3]
           ,0 [IsMultiplePrice]
           ,1 [IsReOrder]
           ,ISNULL([style number],'') [StyleNo]
           ,0 [IsNonTrading]
		     FROM PRODUCTLIST
		
		--select BarCode from InvProductMaster
--truncate table invproductmaster
--		UPDATE InvProductMaster
--SET BarCode = CAST(BarCode AS nvarchar(25));

--select * from AutoGenerateInfo where FormName like '%product%'

--update AutoGenerateInfo set CodeLength=12,Suffix=12 where AutoGenerateInfoID=60

--select * from InvProductMaster

UPDATE PRODUCTLIST SET NEWITEMCODE=ITEMCODE,NEWBARCODE=BARCODE