SELECT * FROM DEPENDANCY 

SELECT * FROM PRODUCTLIST
SELECT distinct SUPPLIERCODE,SUPPLIER FROM PRODUCTLIST
ORDER BY  SUPPLIERCODE

SELECT distinct TYPE FROM PRODUCTLIST

SELECT * FROM InvDepartment
SELECT * from InvCategory
SELECT * FROM InvSubCategory
SELECT * FROM InvSubCategory2

SELECT * FROM INVPRODUCTMASTER WHERE DepartmentID=1

HOMEWARE

UPDATE  INVPRODUCTMASTER SET Department='HOMEWEAR' WHERE Department='HOMEWARE'

SELECT * FROM InvDepartment

SELECT * FROM InvSubCategory3

SELECT * FROM DEPENDANCY WHERE SUBCATEGORY2NAME='BRA'

SELECT * FROM SupplierProperty


SELECT * FROM INVPRODUCTMASTER PM
JOIN InvDepartment D ON PM.Department=D.DepartmentName

UPDATE PM SET PM.DepartmentID=D.INVDEPARTMENTID
FROM InvDepartment D JOIN INVPRODUCTMASTER PM ON PM.Department=D.DepartmentName


UPDATE PM SET PM.CATEGORYID=C.InvCategoryID
FROM INVCATEGORY C JOIN INVPRODUCTMASTER PM ON PM.Category=C.CA





