
UPDATE PM SET PM.DepartmentID=D.INVDEPARTMENTID
FROM InvDepartment D JOIN INVPRODUCTMASTER PM ON PM.Department=D.DepartmentName


UPDATE PM SET PM.CATEGORYID=C.InvCategoryID
FROM INVCATEGORY C JOIN INVPRODUCTMASTER PM ON PM.Category=C.CATEGORYNAME
AND PM.DepartmentID=C.InvDepartmentID
JOIN InvDepartment D ON C.InvDepartmentID=D.InvDepartmentID

UPDATE PM SET PM.SubCategoryID=SC.InvSubCategoryID
FROM INVSUBCATEGORY SC JOIN INVPRODUCTMASTER PM ON PM.SubCategory=SC.SubCategoryName
AND PM.CategoryID=SC.InvCategoryID
JOIN InvCategory C ON SC.InvCategoryID=C.InvCategoryID

UPDATE PM SET PM.SubCategory2ID=SC2.InvSubCategory2ID
FROM INVSUBCATEGORY2 SC2 JOIN INVPRODUCTMASTER PM ON PM.SubCategory2=SC2.SubCategory2Name
AND PM.SUBCategoryID=SC2.InvSubCategoryID
JOIN InvSubCategory SC ON SC2.InvSubCategoryID=SC.InvSubCategoryID

UPDATE PM SET PM.SupplierID=SP.SupplierID
FROM SUPPLIER SP  JOIN INVPRODUCTMASTER PM ON PM.Supplier=SP.SupplierName


SELECT PM.BARCODE,I.BARCODE,* FROM InvProductMaster PM 
JOIN EASYWAY.DBO.TB_ITEM I ON PM.REFERENCECODE1=I.ITEM_CODE

BEGIN TRAN
UPDATE PM SET PM.BARCODE=I.BARCODE FROM EASYWAY.DBO.TB_ITEM I
JOIN InvProductMaster PM ON PM.REFERENCECODE1=I.ITEM_CODE

COMMIT
ROLLBACK


SELECT * FROM InvProductMaster WHERE SubCategory2ID